application: hedgyhedgy
version: 7
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py
    
- url: /ladbrokes
  script: ladbrokes.py
  
- url: /match
  script: match.py
  
- url: /csv
  script: csv.py